### ISSUE TITLE
Read named arguments from a file, SCM or HTTP(S) endpoint

### ISSUE THREAD

**Issue by lmineiro** [zalando-stups/senza#100]
For appliances it is more common to use someone else's senza template and end up providing your own parameters.

Sometimes it could make more sense to just feed the values for those parameters directly from a file or directly from some Git or HTTP endpoint.

For ex., to use the stups-cassandra appliance, directly from https://github.com/zalando/stups-cassandra, one could write a personal stups-cassandra-_myteam_.yaml with parameter values specific to _myteam_:

    EtcdDomain: etcd.myteam.example.com
    ScalyrKey: myteam-specific-scalyr-api-key
    ApplicationId: myteam-stups-cassandra-according-to-yourturn

Such parameter files could be used with a special notation like:

    senza create definition.yaml version @stups-cassandra-myteam.yaml

or

    senza create --params stups-cassandra-myteam.yaml definition.yaml version

Along with https://github.com/zalando-stups/senza/issues/99 this could even become something like:

    senza create \
        --params https://raw.githubusercontent.com/myself/project/master/stups-cassandra-myteam.yaml  \
        https://raw.githubusercontent.com/zalando/stups-cassandra/master/stups-cassandra.yaml \
        cluster1

**Comment by hjacobs** [comment]
Just a note regarding your last comment (read params from HTTP endpoint): I guess this would bring along new problems as parameters will mostly be private and could/should not be read via HTTP without authentication.

**Comment by lmineiro** [comment]
We're now doing something very similar to this using the strategy i described in #155 

That approach still makes the templates long and ugly, not to mention that it allowed me to find the 1024 chars limits for a stack's description:
```
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateStack operation: Template format error: 'Description' length is greater than 1024.
Makefile:23: recipe for target 'deploy' failed
```
