### ISSUE TITLE
confusion between <stack-name> & <stack-name> - <version>

### ISSUE THREAD

**Issue by sstirbu** [zalando-stups/senza#102]
different senza commands have different params regarding stack&version - some may just require version (create), some stack (delete), and some stack-version. The decision in all cases makes sense, but it is very easy to reach a bad situation:
I had two stacks deployed:
cassandra 3
cassandra-test 2

by mistake, I've created a new stack:
cassandra test

to fix things, I've deleted:
cassandra-test

so which stock got deleted? unfortunately cassandra-test version 2.
No serious harm done, this time. But I think the tooling should prevent/alert to such issues.

The docs suggest to use the yaml file name from the stack creation, but ".yaml" is not enforced. The fact that aws naming convention is stack-version makes errors more likely.

Best would be, not to allow creation of a confusing ASG - or a stackname that equals a previous stackname+version or a new stackname+version that equals an existing stackname

**Comment by hjacobs** [comment]
I see your concern, but I'm not sure if Senza should really have code paths (i.e. safety checks) for such rare corner cases.

**Comment by hjacobs** [comment]
@tuxlife I would close this issue, what do you think?

**Comment by tuxlife** [comment]
Sorry, but this is a user fault.

you can't delete a stack with the format `stack_name-stack_version`

senza can't find the stack (exit without any message)

```
$ senza create senza/test5.yaml test latest
Generating Cloud Formation template.. OK
Creating Cloud Formation stack hello-world-test.. OK
$ senza list
Stack Name │Ver.│Status            │Created│Description
hello-world test CREATE_IN_PROGRESS 36s ago Hello World (ImageVersion: latest)
$ senza delete hello-world-test
$ senza list
Stack Name │Ver.│Status            │Created│Description
hello-world test CREATE_IN_PROGRESS 53s ago Hello World (ImageVersion: latest)
```
