### ISSUE TITLE
senza support for named parameters

### ISSUE THREAD

**Issue by sstirbu** [zalando-stups/senza#103]
As the senza yaml files become more and more complex, position base parameters are starting to be quite risky, especially as many params have default values, and one may not notice a change.

It would also be nice to have a senza create --coldrun <name>.yaml that would allow one to see the configured values after the substitutions. 

A standard support for something like senza create <name>.yaml which would show all parameters, and their default values.

We should realize that some stacks are deployed once in a blue moon, and reading the yaml file every time could become cumbersome.

**Comment by hjacobs** [comment]
Named parameters are already supported: see #83 and http://docs.stups.io/en/latest/components/senza.html#senza-info
