### ISSUE TITLE
senza delete: improve output if passed parameters are wrong + improve documentation

### ISSUE THREAD

**Issue by rwitzel** [zalando-stups/senza#118]
P1.
   
    rwitzel@rwit450:~/git/delivery-availability-service$ senza delete delivery-availability-service-1
    rwitzel@rwit450:~/git/delivery-availability-service$ 

Senza should inform the user that it will do nothing here because the arguments are not provided in an appropriate way.

P2.

    rwitzel@rwit450:~/git/delivery-availability-service$ senza delete service-test.yml 1
    Deleting Cloud Formation stack delivery-availability-service-1.. OK
    rwitzel@rwit450:~/git/delivery-availability-service$ 

The output (or the description using -h) should make clear what is deleted and what not (load balancer, etc.).

P3. 

    rwitzel@rwit450:~/git/delivery-availability-service$ senza delete -h
    Usage: senza delete [OPTIONS] [STACK_REF]...
    
      Delete a single Cloud Formation stack
    
    Options:
      --region AWS_REGION_ID  AWS region ID (e.g. eu-west-1)
      --dry-run               No-op mode: show what would be deleted
      -f, --force             Allow deleting multiple stacks
      -h, --help              Show this message and exit.

[STACK_REF] is obviously not right. The name of the service file should be passed. Please fix the documentation.

**Comment by hjacobs** [comment]
@rwitzel you can pass either the YAML file name + stack version OR the stack name + stack version

```
senza del mystack 1
senza del production.yaml 1

**Comment by hjacobs** [comment]
This behavior is consistent with the other commands, e.g.:

```
senza instances mystack 1
senza instances production.yaml 1

**Comment by hjacobs** [comment]
Closing this issue as the behavior is consistent with the other commands and it's correctly shown here: http://docs.stups.io/en/latest/components/senza.html#command-line-usage
