### ISSUE TITLE
Stickiness for LB

### ISSUE THREAD

**Issue by mrandi** [zalando-stups/senza#12]

**Comment by hjacobs** [comment]
I consider this rather low-priority as LB stickiness is considered an anti-pattern IMHO.

**Comment by hjacobs** [comment]
ELB stickyness is already supported by Senza as it allows overwriting all ELB CF properties including "LBCookieStickinessPolicy" and "AppCookieStickinessPolicy" (https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb.html).
