### ISSUE TITLE
TypeError when using multiple IAM roles

### ISSUE THREAD

**Issue by mfellner** [zalando-stups/senza#122]
With a configuration like this:

```yaml
IamRoles:
  - app-drone
  - volume-access
```

An error occurs:
```bash
Generating Cloud Formation template.. EXCEPTION OCCURRED: get_merged_policies() takes 1 positional argument but 2 were given
```

Because get_merged_policies is called with `get_merged_policies(roles, args.region)`:
https://github.com/zalando-stups/senza/blob/master/senza/components/auto_scaling_group.py#L54.

But the method only accepts 1 argument:
https://github.com/zalando-stups/senza/blob/master/senza/components/iam_role.py#L6

**Comment by hjacobs** [comment]
Thanks for reporting this, looks like a bug

**Comment by hjacobs** [comment]
I fixed this bug yesterday :smile: https://github.com/zalando-stups/senza/releases/tag/0.87
