### ISSUE TITLE
senza create: Don't give a false ararm

### ISSUE THREAD

**Issue by nsmolenskii** [zalando-stups/senza#129]
Every single time when I create a new *internet-facing* stack I receive an alarm: 
> You are deploying an internet-facing ELB that will be publicly accessible! You should have OAUTH2 and HTTPS in place!

**As** deploy engineer 
**I want to** suppress this warning into notification.
**So** that makes real errors  more visible and warnings stop [crying 'Wolf'](https://en.wikipedia.org/wiki/The_Boy_Who_Cried_Wolf)

**Comment by hjacobs** [comment]
I agree here, the warning should be less "in the face".
We had to implement this big red error message quickly because of ... well you know ... :smirk:

**Comment by berndherding** [comment]
maybe start on new line and change color to black (but maybe use bold font). just my 2ct.

**Comment by nsmolenskii** [comment]
@berndherding I would say it's will be better to introduce message types, like: error, warning, success and info.
To solve not only this issue but create a good future environment

**Comment by lukasniemeier-zalando** [comment]
:+1:

**Comment by chutium** [comment]
+1
