### ISSUE TITLE
senza patch: allow updating launch configurations and auto scaling groups

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/senza#131]
I propose to add a new Senza command "patch".
The "patch" command should be able to update existing Cloud Formation resources (without using Cloud Formation "update" as this might not be feasible because of DNS traffic switching):

* update launch configurations to use latest Taupage AMI
* update launch configurations with changed Taupage config (different Docker image, environment variables, etc)
* rollout changes for all ASG instances (similar to https://github.com/ImmobilienScout24/aws-ha-updater)

The command line interface could look like:

```bash
# "patch" allows using an existing Senza YAML
# update launch configuration according to current Senza YAML 
# and respawn instances ("apply"):
$ senza patch myapp.yaml 1 --apply  
# or allows patching individual properties (pre-defined patches)
# use latest Taupage AMI and terminate/respawn instances:
$ senza patch mystack 1 --latest-taupage-image --apply

**Comment by hjacobs** [comment]
@tuxlife @sarnowski please provide some feedback to my proposal :bow:

**Comment by hjacobs** [comment]
Rationale for using the name "patch": I think it makes clear that this is something like "hot fixing" or "monkey patching", i.e. circumventing the usual Cloud Formation mechanism (and additionally the "update" command is already taken).

**Comment by hjacobs** [comment]
Disregard my first command line proposal, here a slightly better (more generic / simple) one:

```
# only "patch" the launch configuration
$ senza patch mystack 1 --image=latest 
$ senza patch mystack 1 --image=ami-123
$ senza patch mystack 1 --instance-type=t2.micro
# rollover all EC2 instances safely with new config
$ senza apply-patch mystack 1

**Comment by sarnowski** [comment]
Some suggestions for the "apply-patch" / "rolling-update": https://cloud.google.com/container-engine/docs/kubectl/rolling-update

**Comment by prayerslayer** [comment]
`senza respawn` :godmode:

**Comment by hjacobs** [comment]
First commands are now implemented (in own branch):

Patch:
```
Usage: senza patch [OPTIONS] [STACK_REF]...

  Patch specific properties of existing stack.

  Currently only supports patching ASG launch configurations.

Options:
  --region AWS_REGION_ID         AWS region ID (e.g. eu-west-1)
  --image AMI_ID_OR_LATEST       Use specified image (AMI ID or "latest")
  --instance-type INSTANCE_TYPE  Use specified EC2 instance type
  -h, --help                     Show this message and exit.
```

Respawn:
```
Usage: senza respawn-instances [OPTIONS] [STACK_REF]...

  Replace all EC2 instances in Auto Scaling Group(s)

  Performs a rolling update to prevent downtimes.

Options:
  --region AWS_REGION_ID  AWS region ID (e.g. eu-west-1)
  -h, --help              Show this message and exit.

**Comment by hjacobs** [comment]
The respawn-instances command will currently do the following:

1. Suspend ASG scaling processes AZRebalance, AlarmNotification and ScheduledActions
2. Scale out to current_capacity + 1
3. Wait for all instances to be IN_SERVICE in ELB
4. Terminating one old instance
5. Continue with point 3 until all instances are replaced
6. Resume all scaling processes

**Comment by hjacobs** [comment]
Added patching of user data (e.g. to update Docker image) in https://github.com/zalando-stups/senza/releases/tag/1.0.20
