### ISSUE TITLE
Create inbound rule for different health port

### ISSUE THREAD

**Issue by danielrohe** [zalando-stups/senza#133]
When creating an application security group and the application has a different application and health port (e.g. port 8080 for application request and port 8081 for health requests from LB). The inbound rule of the application's security group only contains the application port. The security group should also contain an inbound rule for the health port.

**Comment by hjacobs** [comment]
Hmm, I think this non-default setup (having a different health check port is not supported by "senza init") should not be supported by "senza init".

Senza "init" only provides a convenient way of bootstrapping Senza definition YAML files (and creating security groups), i.e. it's purpose is not to support all possible configurations.

**Comment by danielrohe** [comment]
Interesting because this setup is supported by the taupage configuration for the appservers and loadbalancers in the yaml file.

**Comment by hjacobs** [comment]
@danielrohe yes, that's right, Senza also supports ALL CloudFormation resources, but the security groups are only created (for convenience) by "senza init" --- i.e. "senza init" will only support a small subset of the most common use cases (e.g. "deploy a standard webapp").

**Comment by hjacobs** [comment]
If you/we see a large demand for a new use cases, we can discuss integrating it into "senza init".
But as you are the first ones demanding/using a different health check port, I would assume that this setup is not common :smirk:
