### ISSUE TITLE
Add "senza destroy" command alias for "delete"

### ISSUE THREAD

**Issue by elgalu** [zalando-stups/senza#135]
New feature request: add alias `destroy` for `delete` as we humans just remember the idea of the thing more than the syntax ;)

```
Usage: senza [OPTIONS] COMMAND [ARGS]...
Error: No such command "destroy".
```

**Comment by sarnowski** [comment]
Please no feature creep. We are also not introducing all kinds of other aliases in other unix commands only that everyone remembers its favorite word. You can easily overcome this issue with your shell `alias senza-destroy="senza delete"`.

**Comment by elgalu** [comment]
Good idea; `alias`, sorry my bad.
