### ISSUE TITLE
enable connection draining on ELB by default

### ISSUE THREAD

**Issue by benjaminwagner** [zalando-stups/senza#140]
Connection draining is essential to ensure that running requests are finished before an instance is removed on scale down. So it should be enabled by default in the CF created by senza.

**Comment by hjacobs** [comment]
Yes, I agree (we already discussed this in the STUPS team some days ago), is 60s a sane default?

**Comment by benjaminwagner** [comment]
60s sounds reasonable

**Comment by hjacobs** [comment]
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb.html#cfn-ec2-elb-connectiondrainingpolicy

**Comment by hjacobs** [comment]
Released in https://github.com/zalando-stups/senza/releases/tag/1.0.18
