### ISSUE TITLE
Make --region parameter top level

### ISSUE THREAD

**Issue by vetinari** [zalando-stups/senza#156]
Please allow the --region parameter for senza, not only for each sub command ->

senza --region some-where-1 create ...

**Comment by hjacobs** [comment]
Actually all commands support the "--region" option, so we could have it on top-level. @vetinari do you have any specific need for it? Using the ~/.aws/config file is anyway the much more convenient way of selecting the AWS region.

**Comment by vetinari** [comment]
Ease of use on the command line :) senza --region some-where-1 list <Enter> <ArrowUp> <Ctrl-W> instances<Enter>.
The config file is ok, when you're in just one region

**Comment by lmineiro** [comment]
:+1:

**Comment by whiskeysierra** [comment]
:+1:

Having it as a top level parameter makes it easier to have an alias with the same name for senza:

    alias west='export REGION=eu-west-1'
    alias central='export REGION=eu-central-1'
    alias senza='senza --region $REGION'

**Comment by hjacobs** [comment]
Fixed with https://github.com/zalando-stups/senza/releases/tag/1.0.46

**Comment by whiskeysierra** [comment]
> Having it as a top level parameter makes it easier to have an alias with the same name for senza:
> 
> alias west='export REGION=eu-west-1'
> alias central='export REGION=eu-central-1'
> alias senza='senza --region $REGION'

FYI, an easier way to do this (even before) is to just set the DEFAULT_AWS_REGION environment variable.
