### ISSUE TITLE
Validate application_id and application_version

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/senza#157]
Senza's TaupageAutoScalingGroup should validate application_id and application_version as we do in Kio (https://github.com/zalando-stups/kio/blob/master/resources/api/kio-api.yaml#L482).

* application_id must match pattern: "^[a-z][a-z0-9-]*[a-z0-9]$"
* application_version must match pattern: "^[A-Za-z0-9](?:[A-Za-z0-9._-]*[A-Za-z0-9])?$"

Background: sometimes users accidentally put the full Docker image (pierone.example.org/../..:123) into application_version

**Comment by jmcs** [comment]
@hjacobs this was already implemented right?

**Comment by hjacobs** [comment]
@jmcs I don't think so, at least it's not validated in https://github.com/zalando-stups/senza/blob/master/senza/components/taupage_auto_scaling_group.py (and this is the only right place to do so)

**Comment by rafaelcaricio** [comment]
I believe there was a typo and the application_version regex should be this pattern:
```
^[A-Za-z0-9]+([._-]?[A-Za-z0-9]+)*$
```

So it can match `v2.4-MASTER` or `1.2.0`

**Comment by jmcs** [comment]
The stack version is checked against `^[a-zA-Z0-9]+$`

**Comment by hjacobs** [comment]
@jmcs yes, stack version MUST have a different regex than the application version / ID. The stack version is more strict because we use it in DNS and it's the last part of CF's stack name (so it cannot contain a slash).

**Comment by jmcs** [comment]
@hjacobs does kio support uppercase in stack names (for example `test-myregion-B`)?

**Comment by hjacobs** [comment]
@jmcs Kio is unrelated to CF stack names/versions (please don't mix them up).
