### ISSUE TITLE
Set VPC ID in configuration

### ISSUE THREAD

**Issue by femueller** [zalando-stups/senza#162]
If there is no VPC marked as default in an AWS account, Senza doesn't find the correct VPC.
A possibility to pass a VPC ID to the Senza config would be a nice improvement.

**Comment by kenden** [comment]
Duplicate of https://github.com/zalando-stups/senza/issues/37 ?

**Comment by femueller** [comment]
@kenden Yes that's exactly the behaviour. Since it's a duplicate, it can be closed.
