### ISSUE TITLE
Senza may compare strings to integers

### ISSUE THREAD

**Issue by gnuton** [zalando-stups/senza#173]
I m running Python 3.4.3 on ubuntu. This problem doesn't seem to exist on mac although.
The problem happens when the yaml file I parse looks like this:

```
SenzaComponents:
   - Configuration:
      Type: Senza::StupsAutoConfiguration

   ##
   ## Elastic Search Master node
   - Master:
      Type: Senza::TaupageAutoScalingGroup
      AutoScaling:
         Minimum: "{{Arguments.Masters}}"                <-----PROBLEM HERE!
         Maximum: "{{Arguments.Masters}}"
         MetricType: CPU
```

All the arguments are read as strings. It's not possible to read them as integer.

Then when senza parse those params,  at line 150 of 
/usr/local/lib/python3.4/dist-packages/senza/components/auto_scaling_group.py

In that line it runs max(as_conf["Minimum"),as_conf.get('DesiredCapacity', 1))
which is max("1", 1) and then It  throws an exception.
```

gnuton@joseph:~/GIT/ESCLUSTER-RO/escluster$ python
Python 2.7.9 (default, Apr  2 2015, 15:33:21) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> "1" > 1
True
>>> 
gnuton@joseph:~/GIT/ESCLUSTER-RO/escluster$ python3
Python 3.4.3 (default, Mar 26 2015, 22:03:40) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> "1" > 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unorderable types: str() > int()
```

**Comment by jmcs** [comment]
[This is already fixed](https://github.com/zalando-stups/senza/blob/93969066061873934b0c59467664ee0418d92c8e/senza/components/auto_scaling_group.py#L153).
