### ISSUE TITLE
search based on stack version and not stack name

### ISSUE THREAD

**Issue by drummerwolli** [zalando-stups/senza#185]
usecase: i have currently multiple stack versions running with the same version, they all a part of "the big stack", e.g.:
- kafka
- the rest api for incoming events
- a consumer
- zookeeper
- the management interface for kafka

to get a faster overview on e.g. all stacks or instances i could do 
```
senza instances | grep <stack_version>
```
but i think its more conventient maybe to have a command in senza built in to look for stacks having the same version. what do you think?

something like this (only a proposal, idk if this is e.g. backward-compatible):
```
senza instances --version=<stack_version>
```

**Comment by outime** [comment]
Hey, sorry for the mess above but I was just testing stuff and forgot these mentions can't be removed... oh well. I like the suggestion and implemented the feature, let's ping @hjacobs to see what he thinks.

**Comment by outime** [comment]
Correction: no need to implement this feature [as it's already available](https://github.com/zalando-stups/senza/pull/206#issuecomment-218294680), so the issue can be closed.

**Comment by hjacobs** [comment]
Uh, actually @drummerwolli wants something else (filter by version ONLY) which is not currently supported, we _MAY_ consider implementing support for this like:

```
senza instances * v123

**Comment by outime** [comment]
@hjacobs you're right, I wasn't very clever yesterday. Would you accept a PR for that?

**Comment by hjacobs** [comment]
@outime yes, we also may discuss the desired behavior first here --- @jmcs and @rafaelcaricio are the new maintainers of Senza, so they might have an opinion, too :smirk:

**Comment by drummerwolli** [comment]
maybe a search based on a regex for stakcname **and** version would be cool as well ...

**Comment by jmcs** [comment]
-1 on regex. I would implement this with [fnmatch](https://docs.python.org/3.5/library/fnmatch.html) as I think this works better on the command line. @rafaelcaricio @hjacobs if you agree with using fnmatch I would implement this.

**Comment by drummerwolli** [comment]
mh, just thought of regex because in fullstop we have regex now to (with -x option) ...

https://github.com/zalando-stups/fullstop-cli/releases/tag/1.0.22

**Comment by rafaelcaricio** [comment]
👍 for `fnmatch`

**Comment by rafaelcaricio** [comment]
Having a second though --- `fnmatch` is non-brainer for things that match files, but regex for all other cases. So I would go with regex in this case.

**Comment by jmcs** [comment]
Regex is more error prone and harder to escape,  shell style matching works much better on the shell (it was built to do exactly that) and it covers most of the use cases.

**Comment by hjacobs** [comment]
@jmcs but you need to escape wildcards on the shell anyway (otherwise it will be expanded by the shell already):

```
$ senza instances '*' v123

**Comment by jmcs** [comment]
Well due to the name limitations on stacks I guess it's hard to make mess with regex anyway, and regex allows one use case I hadn't thought about - matching a version range. So I'll go with regex.

**Comment by hjacobs** [comment]
@jmcs can you document the regex-based stack matching on docs.stups.io ?

**Comment by jmcs** [comment]
@hjacobs  zalando-stups/documentation#76
