### ISSUE TITLE
Occasional NPE in TokenInfoResourceServerTokenServices

### ISSUE THREAD

**Issue by zssonn** [zalando-stups/senza#189]
In the morning between 06:30 and 7:50 we regularly get this NPE in a service running in AWS using stups-spring-oauth2-server in version 1.0.11-RC1:

Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: Mar 05, 2016 6:38:53 AM org.apache.catalina.core.StandardWrapperValve invoke
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: java.lang.NullPointerException
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.zalando.stups.oauth2.spring.server.TokenInfoResourceServerTokenServices.loadAuthentication(TokenInfoResourceServerTokenServices.java:117)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationManager.authenticate(OAuth2AuthenticationManager.java:83)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:150)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:120)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:53)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:262)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:87)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:121)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
Mar  5 06:38:53 ip-172-31-169-157 docker/d48e5bd14e9b[838]: #011at java.lang.Thread.run(Thread.java:745)

This exception is only logged once or twice a day and I can't reproduce it manually. It seems that getMap() returns null in these cases.
The NPE does not appear in a service that uses stups-spring-oauth2-server in version 1.0.7.

**Comment by hjacobs** [comment]
@zssonn sorry, that's obviously the wrong repository for the issue -- this should be the correct one: https://github.com/zalando-stups/stups-spring-oauth2-support

(GitHub code search can quickly tell you in which repo a class resides)
