### ISSUE TITLE
Use Alias Route 53 records instead of CNAMEs

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/senza#197]
http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-choosing-alias-non-alias.html?tag=duckduckgo-d-20

Why change from CNAME to Alias records?
* Alias records allow you to use Senza with your “root” team domain (e.g. you can create a stack serving “myteam.example.org”)
* Alias records allow having TXT or MX records with the same domain name
* Alias records avoid one DNS lookup (clients need to lookup CNAME, afterwards resolve the target to the IP)
* You can optionally enable “Evaluate Target Health” to have a DNS failover (AWS will only direct traffic to the Alias target if ELB health is OK)

**Comment by duergner** [comment]
That would be a great feature for us. We're having a zone where we need to deploy a stack using a subdomain that also has TXT and MX records attached we cannot get rid of.

**Comment by jmcs** [comment]
*Mostly* note to self: [Using RecordSetGroup to Set Up an Alias Resource Record Set](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-route53.html#scenario-recordsetgroup-zoneapex)

**Comment by jmcs** [comment]
Alias records can't be used if cname records already exist for a domain name, so I'll implement a fallback if a cname record is detected for a domain name.

**Comment by tuxlife** [comment]
Please don't use a Fallback. Please add a migration function to migrate all
cnames to alias


Gruß,
Matthias

-- Matthias Kerk | +49 30 2000 88 324 | +49 176 12 758 240 |
matthias.kerk@zalando.de


2016-07-12 13:24 GMT+02:00 João Santos <notifications@github.com>:

**Comment by hjacobs** [comment]
@jmcs can you document the change here as a comment and how it works (we need to put into release notes too)?

Some relevant changes:

* `dig mystack.example.org` will no longer "reveal" the current active version
* dangling DNS records will cause trouble (see PR comment)
* DNS caching behavior might be different
* "main_dns" column of `senza status ...` no longer works

**Comment by hjacobs** [comment]
"main_dns" column of senza status will now work on resolved IP address, you can use “senza status” to see whether your local DNS resolves to the right stack version (as “dig” no longer easily reveals this information)

**Comment by hjacobs** [comment]
Senza will ask you to migrate existing DNS records from CNAME to Alias the first time you deploy with the new Senza version or update the traffic of a stack. Route53 records pointing to non-existing\deleted ELBs can't be converted and will be deleted.

**Comment by hjacobs** [comment]
Overall the benefits of Alias records made us drop CNAME support in Senza (when creating DNS records). Reading old CNAME DNS records will still be supported for the foreseeable future.
