### ISSUE TITLE
Change instance profile setting to roles list

### ISSUE THREAD

**Issue by sarnowski** [zalando-stups/senza#2]
It would be nice to be able to specify a list of roles instead of one instance profile ID. Senza should generate an instance profile on-the-fly with all roles attached. This is especially helpful as not all types of roles automatically have an instance profile ID. This way its also easier to compose different roles for the server (which will be important for getting credentials via berry).

See simplestack: https://github.com/zalando/simplestack/blob/master/resources/simplestack/template.json#L134

**Comment by hjacobs** [comment]
+1
