### ISSUE TITLE
Confirmation of Senza delete 

### ISSUE THREAD

**Issue by lfischer** [zalando-stups/senza#203]
To prevent accidently deletion of a stack, it would be safer to promt for a confirmation.
For scripted usage, a --force option to skip the confirmation would be helpful.

**Comment by hjacobs** [comment]
@lfischer I would disagree as that would be inconvenient --- right now we already make sure that at most one stack is deleted and require "--force" for deleting more than one stack.

**Comment by jmcs** [comment]
Maybe having a `-i` flag like `rm` makes sense, then it would be easy to change the behaviour with an alias.

**Comment by hjacobs** [comment]
@jmcs yes `-i` to prompt sounds good --- but I would only implement/add this if this is upvoted by other people...

**Comment by lfischer** [comment]
@jmcs `-i` would be a good and not invasive solution

**Comment by lfischer** [comment]
This was quick! Thanks a lot. :)
