### ISSUE TITLE
Add flag to expose error instead of writing it to a file

### ISSUE THREAD

**Issue by rafaelcaricio** [zalando-stups/senza#238]
Would be nice to have a option to explicitly tell Senza to show the unknown exception stack trance in the console instead of writing it to a file.

### Current behaviour

It shows this message:
```
Unknown Error.
  Please create an issue with the content of /var/folders/90/pz80sxl93gl11zjsbmylwmxj42vx03/T/senza-traceback-_bv0iaac
```

### Expected behaviour
In case of calling Senza with something like `senza create broken.yaml --stacktrace-visible` then it would simply display the whole stack trace of the error in the console.

### Why?

It is important for tools like Lizzy that call Senza commands in background be able to pipe the actual errors that are happing while running Senza to the logs.

**Comment by hjacobs** [comment]
@rafaelcaricio I would actually always at least show the exception message.

**Comment by hjacobs** [comment]
Having another option (and run again) is as inconvenient as looking into the stacktrace file.

**Comment by rafaelcaricio** [comment]
In case of Lizzy it would always run with this flag active. And indeed the
default message has to be improved anyways.
