### ISSUE TITLE
Support "senza update"

### ISSUE THREAD

**Issue by sarnowski** [zalando-stups/senza#27]
$ senza update
should trigger a stack update. that is useful for stateful applications in order to leverage the rolling update policies of cloud formation

**Comment by hjacobs** [comment]
will check, but it's not the highest prio on my list right now

**Comment by schlomo** [comment]
Maybe it is worth to take some stuff from https://github.com/ImmobilienScout24/aws-ha-updater

**Comment by feikesteenbergen** [comment]
For spilo and the cassandra appliance this feature would be very welcome.

Example usecases:

- minor PostgreSQL updates
- different instance types (up/downscaling)

**Comment by tuxlife** [comment]
a option for instance termination is also nice...

**Comment by tuxlife** [comment]
@feikesteenbergen, @schlomo, @sarnowski Can you please test this Branch?
