### ISSUE TITLE
senza delete non existing stack should show error or warning

### ISSUE THREAD

**Issue by PetrGlad** [zalando-stups/senza#276]
`senza delete someid` (or `senza delete someid someotherid`) completes silently without any output but also does nothing. The behavior is confusing. `senza` should print some warning message that stack is not found.
Also if invocation of `senza delete` with single argument is not expected then `senza` should show a usage message.

(used Senza 1.0.84)

**Comment by PetrGlad** [comment]
Just found out that (some?) other commands that require stack version also fail silently. E.g. `senza scale`

**Comment by jmcs** [comment]
For delete this is fixed on master, we just have to release a new version.

**Comment by hjacobs** [comment]
Released in https://github.com/zalando-stups/senza/releases/tag/1.0.88
