### ISSUE TITLE
No module named "typing"

### ISSUE THREAD

**Issue by whiskeysierra** [zalando-stups/senza#287]
After installing stups-senza-2.0.96 (via `pip3 install --upgrade stups`) I got this

```
$ senza list
Traceback (most recent call last):
  File "/usr/local/bin/senza", line 7, in <module>
    from senza.cli import main
  File "/usr/local/lib/python3.4/dist-packages/senza/cli.py", line 39, in <module>
    from .manaus.route53 import Route53
  File "/usr/local/lib/python3.4/dist-packages/senza/manaus/route53.py", line 5, in <module>
    from typing import Any, Dict, Iterable, Iterator, List, Optional, Union, Tuple
ImportError: No module named 'typing'
```

This fixed it `sudo pip3 install typing`.

**Comment by hjacobs** [comment]
@whiskeysierra what Python version are you using? @jmcs introduced the `typing` module and loads it in `setup.py` if necessary (https://github.com/zalando-stups/senza/blob/master/setup.py#L108) --- Python 3.5 comes with `typing` out of the box (https://docs.python.org/3/library/typing.html), it's only necessary to install in 3.4.

**Comment by whiskeysierra** [comment]
```
$ python3 --version
Python 3.4.3+
```

**Comment by hjacobs** [comment]
@jmcs could you check why your conditional dependency does not work? Maybe it's because of "wheel" packages? Could we just always depend on the `typing` module?
