### ISSUE TITLE
Taupage 'application_id' cannot have a substituted vaue

### ISSUE THREAD

**Issue by danmanirl** [zalando-stups/senza#307]
Since updating senza the lines 
```
...
TaupageConfig:
        application_id: "{{ Arguments.ApplicationId }}"
...
```

give the error:
```
Generating Cloud Formation template.. EXCEPTION OCCURRED: Application id must satisfy regular expression pattern "^[a-z][a-z0-9-]*[a-z0-9]$"
```

If I do not use argument expansion it works fine i.e.:
```
...
TaupageConfig:
        application_id: "my-amazing-application-name"
...
```

This worked for previous versions of senza, but now it looks like the validation is done before expanding the vars?

**Comment by hjacobs** [comment]
@danmanirl can you check what `Arguments.ApplicationId` contains?

I'm pretty sure that argument expansion still works as all our Senza definitions contain something like `application_version: "{{Arguments.ImageVersion}}"` :smirk:

**Comment by danmanirl** [comment]
So after trying with a minimal senza file I could not reproduce the issue. Something strange going on with our senza file.  Closing.
