### ISSUE TITLE
Support for Application Load Balancers

### ISSUE THREAD

**Issue by arjunrn** [zalando-stups/senza#310]
AWS just released a new Load Balancer [type](https://aws.amazon.com/blogs/aws/new-aws-application-load-balancer/) with support for HTTP2. There is already support for it in Cloudformation. We could have a new component likewise called `Senza::WeightedDnsApplicationLoadBalancer`.

**Comment by prayerslayer** [comment]
Properties of the ELB have been split up in multiple components for the ALB, and some were added.

* [LoadBalancer](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html): Basically `scheme`, `securityGroup`, `subnet`.
* [Listener](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-listener.html): `port`, `protocol`, `certificates`
* [ListenerRule](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-listenerrule.html): Use this to forward requests to target groups based on the request path
* [TargetGroup](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-targetgroup.html): Describes a set of EC2s along with health check config, VPC and such.

The ALB is awesome* as we could do something like this(?):

* Create ALB once with DNS record pointing to it, in separate CF stack
* Application stack contains TargetGroup for the ALB which points to its AutoScaling group (hope this works)
* Application stack also contains ListenerRule for the ALB stating when to route requests to it (e.g. for requests to `/api/*`

:scream:

* Somehow you can't route based on headers yet.

**Comment by arjunrn** [comment]
It might be easier to just have another component in the same stack. I don't think many microservices will have a requirement for path based routing since that would be handled in something like Skipper anyway. So just use a match all wildcard like `/*` and use it exactly like the Classic LB. Maybe @hjacobs or @tuxlife could pitch in as well with their opinions.

**Comment by jmcs** [comment]
I agree that it's better to have another component to avoid breaking things that are working now.

**Comment by hjacobs** [comment]
We should probably introduce a new component, but AWS guys advice us to switch to ALB for everything  HTTP-based (some under-the-hood performance improvements etc).

So I would say:

* introduce new component (with "V2" suffix)
* switch default `senza init` templates to use the new component

We also need to support the new ELBv2 in ZMON AWS agent!

**Comment by hjacobs** [comment]
Basic support for Application Load Balancers with HTTP/2 was released in https://github.com/zalando-stups/senza/releases/tag/2.0.121

Still TODO: support ELBv2 metrics in `senza health`

**Comment by hjacobs** [comment]
Still TODO: 

* fix healthy instances count in `senza status`
* fix healthy instances count in `senza health`
