### ISSUE TITLE
Shrink "description" field to allowed 1024 chars

### ISSUE THREAD

**Issue by Jan-M** [zalando-stups/senza#330]
This seems to pop up more and more, I see no real reason why senza should not just do

description[:1024]

to fix this for everyone.

**Comment by hjacobs** [comment]
For reference: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-description-structure.html

**Comment by scherniavsky** [comment]
The same error appeared to me after adding 2 ~130 char-long Kms strings to Senza params. Shrinking any of them, so the total length of all params values doesn't exceed 640 chars, works (descriptions are left intact).  http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cloudformation-limits.html - doesn't seem to me like a CF template limitation.

**Comment by hjacobs** [comment]
Released in https://github.com/zalando-stups/senza/releases/tag/2.0.121
