### ISSUE TITLE
Fail on deletion of a stack with traffic

### ISSUE THREAD

**Issue by lenalebt** [zalando-stups/senza#343]
Current behaviour of senza when deleting a stack with 100% traffic is to silently remove the stack and DNS entries, which leads to "unknown host" for all users. This is potentially error-prone and can lead to downtimes in production. It would be better if it does one of the following

* either die and not allow to delete an instance that has (full / any) traffic
* or route traffic to one of the other stacks that already have traffic

Imho, the first proposal makes more sense, and the latter might make sense in case you have e.g. two stacks with traffic.

**Comment by hjacobs** [comment]
@lenalebt is #292 solving the issue for you?

**Comment by lenalebt** [comment]
@hjacobs no, I don't think so. Current workload does not allow for it (would take me some time to get into Python again to make it good, not my day-to-day-language).
