### ISSUE TITLE
Allow for setting AvailabilityZones property in Auto Scaling Group definition

### ISSUE THREAD

**Issue by regispl** [zalando-stups/senza#377]
Looking at [this code](https://github.com/zalando-stups/senza/blob/cbe977e9c928754bb2dfab9b48bacd36aa32da6f/senza/components/auto_scaling_group.py#L13) it seems like the [AvailabilityZones property](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#cfn-as-group-availabilityzones) is not allowed / intentionally ignored in Auto Scaling Group definition. Is there any specific reason for it? Would it be possible to enable it?

**Comment by hjacobs** [comment]
@regispl the `AvailabilityZones` property is not necessary as we pass the actual subnets via [VpcZoneIdentifier](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#cfn-as-group-vpczoneidentifier). You can set the `AvailabilityZones` property on our `StupsAutoConfiguration` instead (this is required for using existing EBS volumes, see http://docs.stups.io/en/latest/user-guide/storage.html).
