### ISSUE TITLE
add param --update-if-exists to senza create to make it idempotent

### ISSUE THREAD

**Issue by kenden** [zalando-stups/senza#416]
It would be nice if we got the same result when calling `senza create` several times with the same parameters.
At the moment, the second time `senza create` is called, we get an error 'Stack already exists`.

It would be useful to have a parameter like `--update-if-exists`.

That might require to add a function to check if the stack name exists, and redirect to `senza update` if it returns True. 

Right now we have a bit of bash to do this:
```
stack_name=$(grep 'StackName:' "${SENZA_TEMPLATE}" | awk '{print $2}')

# check if stack exists
if [[ ! -z $(senza --region ${EC2_REGION} list --output tsv | awk '{print $1 ":" $2}' | grep ${stack_name}:${STACK_VERSION}) ]]; then
  echo "Stack '${stack_name}' exits. Updating..."
  senza_command=update
else
  echo "Stack '${stack_name}' does not exit. Creating..."
  senza_command=create
fi

# create/update stack
senza "${senza_command}" \
    --stacktrace-visible \
    --region "${REGION}" \
    --parameter-file "${SENZA_PARAM_FILE}" \
    "${SENZA_TEMPLATE}" \
    "${STACK_VERSION}" \
    dockerTag="${TAG}"
```

However in a Makefile, this gets so ugly that we put it in a separate shell script. 
And that results in having to pass all those variables (REGION, SENZA_PARAM_FILE, SENZA_TEMPLATE, STACK_VERSION, TAG) from the Makefile to the shell script, which means the script itself becomes something to maintain... 

It'd be nice to just have this:
```
senza create \
    --update-if-exists \
    --stacktrace-visible \
    --region "${REGION}" \
    --parameter-file "${SENZA_PARAM_FILE}" \
    "${SENZA_TEMPLATE}" \
    "${STACK_VERSION}" \
    dockerTag="${TAG}"
```

**Comment by hjacobs** [comment]
I think this feature request makes sense. @kenden can you elaborate on "why" you are running create/update multiple time on the stack without knowing whether it exists? Would be good too know the exact use case.

**Comment by kenden** [comment]
When updating the dockerTag of an existing stack, we know the stack exists, yes.

But if we create copies of the stack to check a variation, or create a new repo with the same deploy code, it's nice to not have to worry about the stack existing or not.

Or what if (knock on wood), the stack gets deleted? We'd need to recreate it manually, it wouldn't work in the CI.

**Comment by musiKk** [comment]
I have another use case for this. We may want to run tests on a system close to what's deployed live but on integration (especially load tests). This involves deploying a particular version and altered parameters compared to what normally runs on integration (live has beefier hardware for example). Integration is usually a mix of released versions and development versions. Currently I have to compare all those versions and decide whether to use `update` or `create` based on whether the version is different or not.

By way of example, consider I have services A and B with versions 1.1 and 1.5 deployed on live respectively and 1.1 and 1.6-dev deployed on integration respectively. I'd need `update` for the 1.1 and `create` for the 1.6-dev. It would be great to be able to just say something akin to `upsert A 1.1` and `upsert B 1.5`, switch traffic and be done with it.

(Don't get hung up on the term _upsert_. Whether it's a new command or a flag for an existing command doesn't really matter much.)
