### ISSUE TITLE
Show Taupage AMI version in senza instances

### ISSUE THREAD

**Issue by BGehrels** [zalando-stups/senza#45]

**Comment by hjacobs** [comment]
:+1:

**Comment by hjacobs** [comment]
Maybe there should be a new Senza command to see AMI images and their usage (e.g. to check which instances run an outdated Taupage AMI)

**Comment by hjacobs** [comment]
Added a new "senza images" command to list available and used Taupage AMIs: http://docs.stups.io/en/latest/components/senza.html#command-line-usage
