### ISSUE TITLE
special characters within parameters are made html safe

### ISSUE THREAD

**Issue by imduffy15** [zalando-stups/senza#459]
Mustache appears to be doing some escaping on parameters by default.

The following was passed as a parameter:

```
jdbc:postgresql://localhost:5432/database?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
```

It was then used as an environment variable:

```
TaupageConfig:
    environment:
        JDBC_URL: "{{Arguments.jdbcUrl}}"
```

In the instance userdata script the following was seen:

```
jdbc:postgresql://localhost:5432/database?ssl=true&amp;sslfactory=org.postgresql.ssl.NonValidatingFactory
```

Note the `&amp;` which resulted in the application failing to deploy.

Workaround for now, was to use `JDBC_URL: "{{{Arguments.jdbcUrl}}}"` as the environment variable not the three braces instead of two. Didn't see this workaround documented anywhere.

**Comment by hjacobs** [comment]
@imduffy15 yes, I was aware of this problem, but I never ran into it (never passed something with "&" as parameter). Feel free to open a PR here or in stups-docs to document the workaround.

**Comment by imduffy15** [comment]
PR opened, closing.

https://github.com/zalando-stups/documentation/pull/114

**Comment by inikolaev** [comment]
The workaround helped me a bit, but I still get incorrect result: `&` is being replaced with `\u0026`.
@hjacobs @imduffy15 have you experienced anything like that? 
My use-case is similar - I'm trying to put JDBC connection string into a separate parameters file.
