### ISSUE TITLE
Senza scale should ask when scaling multiple versions

### ISSUE THREAD

**Issue by elezar** [zalando-stups/senza#478]
Yesterday, I was scaling a stack with two versions and executed:
```
$ senza scale STACKNAME 0
```
this scaled **BOTH** versions of the stack to 0 instances. I corrected this with a subsequent scale command, but this left the stack in a state where the minimum number of instances was 0 and this caused an incident later at night.

**My expectation** was that `scale` would behave the same as `delete` in that it asks for confirmation when scaling a stack with multiple versions present.

**Comment by vadeg** [comment]
This issue was merged and can be closed, no?

**Comment by elezar** [comment]
Thanks. Closing this issue.

(Note I don't have a means to currently test this, but I did have a look at the merged PR)
