### ISSUE TITLE
senza list wrong line length

### ISSUE THREAD

**Issue by schlomo** [zalando-stups/senza#48]
When running `senza list`without a stack name the output is broken:

![image](https://cloud.githubusercontent.com/assets/101384/8078499/7e74775a-0f5e-11e5-9e89-16b509c39f6e.png)

When I run `senza list <stackname>` then it is fine:

![image](https://cloud.githubusercontent.com/assets/101384/8078527/997b436c-0f5e-11e5-9012-1899204a8bc1.png)

I tried looking into the code but could not understand where the problem comes from.

(OSX 10.10, python 3.4.3 from homebrew and `pip3 install stups`)

**Comment by hjacobs** [comment]
Thanks for the bug report

**Comment by tuxlife** [comment]
This is not a Bug...
This is a Feature...

The header is as long as the longest content.
