### ISSUE TITLE
Not Possible to use "HealthCheckProtocol: HTTPS" for ElasticLoadBalancers in senza template.

### ISSUE THREAD

**Issue by rashamalek** [zalando-stups/senza#481]
It is not possible to use SSL:443 with the /status endpoint.
Endpoint use is only in HTTP and HTTPS modes available.

ALLOWED_HEALTH_CHECK_PROTOCOLS could be adapted to enable HTTPS protocol use in Heathchecks for ElasticLoadBalancers.

**Comment by jmcs** [comment]
Fixed by #480
