### ISSUE TITLE
Senza does not recognize referenced Security Groups

### ISSUE THREAD

**Issue by drummerwolli** [zalando-stups/senza#63]
senza currently only supports Security Groups which are already created beforehand, not the ones created in the Resources section. Should be supported the same way as IAM roles, or is there a reasons why this is not yet implemented?

**Comment by hjacobs** [comment]
:+1: for supporting "Ref" in the Senza definition, please add a unit test for this case, too

**Comment by hjacobs** [comment]
This issue was done and works.
