### ISSUE TITLE
Senza "init" should check whether mint S3 bucket exists

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/senza#67]
Currently we create mint S3 buckets in eu-west-1 only, i.e. running Senza in eu-central-1 will lead to a wrongly configured mint S3 bucket (in TaupageConfig).

**Comment by tuxlife** [comment]
@hjacobs Why create we only one mint Buket and not one per region?

**Comment by tuxlife** [comment]
https://github.com/zalando-stups/senza/releases/tag/0.65
