### ISSUE TITLE
Add some special variables that can be used in the templates

### ISSUE THREAD

**Issue by lmineiro** [zalando-stups/senza#71]
It would be nice to be able to reference "Well Known Variables" to the senza templates like:
- AWS Account ID
- Region
- MainDomain
- TeamID
- ...

We could use them in some of the conventions we've been using like the mint bucket, etcd cluster and many others:

```
      TaupageConfig:
        etcd_discovery_domain: "etcd.{{Variables.MainDomain}}"
        mint_bucket: "zalando-stups-mint-{{Variables.AccountId}}-{{Variables.Region}}"
```

**Comment by tuxlife** [comment]
It was a hidden feature :relaxed:

https://docs.stups.io/en/latest/components/senza.html#senza-info

is it okay for you?

**Comment by tuxlife** [comment]
Live in Version 0.71
