### ISSUE TITLE
Enable request rate throttling for instance list

### ISSUE THREAD

**Issue by bocytko** [zalando-stups/senza#81]
I would like to check the health of all my instances. I'm happy to wait longer if it's needed.
Currently with > 25 stacks I get an "Rate exceeded" error response when executing "senza inst".

It would be cool if I could provide a value from the command line, which would enable rate limiting with a certain factor (N times higher delay between requests) or similar.

```
  File "/usr/local/lib/python3.4/dist-packages/boto/connection.py", line 1186, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.BotoServerError: BotoServerError: 400 Bad Request
<ErrorResponse xmlns="http://elasticloadbalancing.amazonaws.com/doc/2012-06-01/">
  <Error>
    <Type>Sender</Type>
    <Code>Throttling</Code>
    <Message>Rate exceeded</Message>
  </Error>
  <RequestId>...</RequestId>
</ErrorResponse>
```

**Comment by hjacobs** [comment]
One idea would be to allow "ignore throttling", i.e. just skip ELB status result (in the instances list) as soon as rate limit is exceeded

**Comment by bocytko** [comment]
Sounds fine for the start as well.

**Comment by hjacobs** [comment]
"Throttling" error code is ignored for ELB instance status retrieval as of version 0.68
