### ISSUE TITLE
Improve senza create command line parameters handling

### ISSUE THREAD

**Issue by a1exsh** [zalando-stups/senza#83]
Surprisingly, I couldn't find this being brought up before, so here goes.

Senza create doesn't check for extra parameters on the command line.  Nor can it help you if you misplaced a parameter.  And you have to put them in the certain order, dictated by the .yaml file.

Imagine a .yaml where two numeric parameters follow one another: you run

    senza create my.yaml bla-bla-bla 3 60 <image> ...

but you have misplaced the params, and instead of 3 instances with some check timeout of 60 seconds you are now creating 60 instances with 3 seconds timeout!  So to avoid that you have to keep the .yaml file before your eyes in order to check the order of the parameters.

Wouldn't it be more convenient to provide parameters as key=value?  You can then specify them in any order and the command line becomes self-documenting, e.g.:

    senza create my.yaml APPID=bla-bla-bla NODES=3 TIMEOUT=60 IMAGE=<image> ...

I think for backwards compatibility, we could also keep the current positional approach and support a mix of them (like the Python itself does by the way).

Cheers!

**Comment by hjacobs** [comment]
Similar issue: https://github.com/zalando-stups/senza/issues/70

**Comment by a1exsh** [comment]
So I guess #70 could be implemented on top of this.  I'll try to see if I can prepare a patch.

**Comment by hjacobs** [comment]
@a1exsh merged and released (v. 0.67) -- could you do a PR on the documentation, too?

**Comment by a1exsh** [comment]
Cool, thanks - will do.
