### ISSUE TITLE
Senza Init should proactively ask whether the ELB should be public ("internet-facing") or not

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/senza#91]
Senza "init" should ask whether the load balancer should be public ("internet-facing" ELB) or internal.

```
Do you want to create a public or internal load balancer?

1) public: internet-facing ELB reachable by everyone
2) private: internal ELB only reachable from within the VPC
```

**Comment by hjacobs** [comment]
See 
* http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/elb-internet-facing-load-balancers.html
* http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/elb-internal-load-balancers.html

**Comment by hjacobs** [comment]
@tuxlife this is now done I believe?

**Comment by tuxlife** [comment]
Done with Version 0.72
