### ISSUE TITLE
Support "internal" ELB in Elastic Load Balancer component

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/senza#92]
Required for #91 : https://github.com/zalando-stups/senza/blob/master/senza/components/elastic_load_balancer.py#L85

* Support selecting the "scheme" of the ELB
* Support internal load balancer subnets

Obviously the current behavior needs to stay (default: internet-facing).

**Comment by hjacobs** [comment]
Internal ELBs are mostly useful for internal persistence "tiers" such as Solr, which should not be exposed to the public (and which mostly have no authentication support).

**Comment by harti2006** [comment]
:+1:

**Comment by roskenet** [comment]
:+1:

**Comment by tuxlife** [comment]
Live in Version 0.71
