### ISSUE TITLE
Access logs for ELB

### ISSUE THREAD

**Issue by mrandi** [zalando-stups/senza#93]
Activate by default ELB logs.

https://aws.amazon.com/blogs/aws/access-logs-for-elastic-load-balancers/

**Comment by harti2006** [comment]
This needs a bucket with proper permissions. Could be initialized with seven-seconds.

http://docs.aws.amazon.com/ElasticLoadBalancing/latest/DeveloperGuide/enable-access-logs.html

**Comment by tuxlife** [comment]
I would not mix the tools and would not set as default.

But we should support this option!

:+1:

**Comment by hjacobs** [comment]
Senza now supports setting any ELB properties (see https://github.com/zalando-stups/senza/releases/tag/0.74), i.e. users can enable access logs if they want/need to.
I will close this issue.
