### ISSUE TITLE
Allow direct pull of template definitions from HTTP(s)

### ISSUE THREAD

**Issue by lmineiro** [zalando-stups/senza#99]
Most appliances don't require downloading or installing anything locally apart from the STUPS tooling, namely mai and senza. Usually there are also Docker images deployed to some public registry.

It would make the experience a lot more straightforward to just fetch the template from a remote HTTP(S) endpoint skipping the need to download or git clone first.

e.g.
``senza create https://raw.githubusercontent.com/zalando/stups-cassandra/master/stups-cassandra.yaml green etcd.myteam.domain.com``

**Comment by lmineiro** [comment]
I had a quick look at this during the weekend and it seems that urllib.request.urlopen would do it, although it required some tweaking with local file paths.

**Comment by tuxlife** [comment]
Live in Version 0.73
